web_modules/GoogleAnalyticsTracker/index.js

See https://github.com/MoOx/phenomic/issues/531 for more information

Better Google Analytics tracking

---

scripts/copy-stylelint-docs.js
web_modules/Demo/index.css
web_modules/Demo/index.js
web_modules/Navigation/index.css
web_modules/Navigation/index.js
web_modules/app/routes.js
web_modules/layouts/DemoPage/index.css
web_modules/layouts/DemoPage/index.js

Refs #2 
The content of the demo page is just an iframe pointing to http://stylelint-demo.herokuapp.com

Add a 'Demo' page

---

src/components/Navigation/index.css

Evenly space navigation items

---

plugins/remark-stylelint-pattern-validity/index.js

Ref: https://github.com/stylelint/stylelint/pull/2388#discussion_r103114457

Account for singular valid and invalid examples

---

plugins/remark-stylelint-pattern-validity/index.js

Ref: https://github.com/stylelint/stylelint/pull/2510

Update plugin for new violation wording

---

src/layouts/Page/index.js

fix- use phenomic 404 page #44

---

.npmrc

Same as for [stylelint](https://github.com/stylelint/stylelint/blob/b4b6d19f13b64610a38d19432d62b4f753ef426a/.npmrc) repository.

Disable package-lock.json

---

.travis.yml

Bump Node.js version to 8 in Travis

---

package.json
plugins/loader-plugin-markdown-init-head.title-property-from-content/index.js
plugins/loader-plugin-markdown-transform-body-property-to-html/index.js
plugins/remark-stylelint-pattern-validity/index.js
plugins/remark-stylelint-url/index.js
postcss.config.js
scripts/copy-stylelint-docs.js
scripts/phenomic.browser.js
scripts/phenomic.node.js
src/AppContainer.js
src/components/Container/index.js
src/components/Content/index.js
src/components/DefaultHeadMeta/index.js
src/components/Demo/index.js
src/components/DocSearch/index.js
src/components/Footer/index.js
src/components/GoogleAnalyticsTracker/index.js
src/components/Header/index.js
src/components/Loading/index.js
src/components/Navigation/index.js
src/layouts/DemoPage/index.js
src/layouts/Page/index.js
src/layouts/PageError/index.js
src/layouts/RulePage/index.js
src/metadata.js
src/routes.js
src/store.js
webpack.config.js

Same setup as we use for the stylelint repository. Prettier uses default settings. [lint-staged](https://github.com/okonet/lint-staged) ensures new code is formatted.

Add Prettier and setup precommit hook for it

---

src/AppContainer.js
src/utils/isChrome.js
src/utils/isSafari.js

Fixes Anchor links don't work if you just go by URL in #58 
Looking forward to your feedback

Fix scroll to url fragment on initial load in Chrome

---

package.json
scripts/generate-stylelint-docs.js

Closes #69 
Via the [`remark-inline-links`](https://github.com/remarkjs/remark-inline-links) plugin.
The generated `docs/CHANGELOG.md` file changes like this: 
```diff
-## [10.1.0][]
+## [10.1.0](https://github.com/stylelint/stylelint/compare/10.0.1...10.1.0)
```

Fix changelog Table of Content

---

scripts/generate-stylelint-docs.js

Add hosting info to the main page

---

.github/workflows/nodejs.yml
.travis.yml

Following direction from the mail repository.

Use Github Actions instead of Travis

---

website/static/css/custom.css

Add link hover, fix site header width

---

package.json
scripts/generate-stylelint-docs.js

Hopefully closes https://github.com/stylelint/stylelint.io/issues/92
It's just a shot to the sky, because it's not clear what causing fail. Logs has:
> 2:03:18 PM: Shutting down logging, 159 messages pending
So maybe extensive logging causing some troubles.

Fix failing deploys

---

scripts/generate-stylelint-docs.js

Fix missing link to changelog on /developer-guide/releases

---

package-lock.json
package.json
scripts/generate-stylelint-docs.js
scripts/sidebars-template.json
website/core/Footer.js
website/siteConfig.js
website/static/css/custom.css

Closes #128 
You'll need to pull down the https://github.com/stylelint/stylelint/pull/4561 branch of stylelint and use that preview this change locally.

Adapt to new docs structure

---

package-lock.json
package.json
scripts/sidebars-template.json

New page introduced in https://github.com/stylelint/stylelint/pull/4592
---
I've also temporarily updated that branch of stylelint so that the deploy preview works.  I will revert the change before merging the PR.
This is ready for review.

Add the new syntaxes page to the sidebar

---

scripts/generate-stylelint-docs.js

Closes #139 
I'm not sure why the links aren't being rewritten automatically. The kink will probably work itself out when we update to docusaurus@2.

Fix links to contributing

---

.gitignore
.npmpackagejsonlintignore
.prettierignore
package-lock.json
package.json
scripts/generate-stylelint-docs.js
scripts/sidebars-template.json
website/core/Footer.js
website/package.json
website/pages/en/demo.js
website/siteConfig.js
website/static/js/pattern-validity.js

Use our ESLint and Prettier configs.

Use our configs

---

website/package-lock.json

None.
This change is generated by the `npm audit fix` command.
Fixed vulnerable dependencies:
- browserslist
- hosted-git-info
- lodash
See <https://github.com/stylelint/stylelint.io/security/dependabot>

npm audit fix for website/

---

.github/workflows/nodejs.yml

See also stylelint/stylelint#5481
- Bump actions/setup-node from v1 to v2
- Enable caching for actions/setup-node
- See <https://github.com/actions/setup-node#caching-packages-dependencies>
- Split `npm ci` and `npm test` into each step

Update CI configuration

---

README.md

This is a documentation suggestion to link to the doc files for people who want to edit them. I had a really hard time finding them due to the broken links on the website, and this would have made it significantly easier.
It's pretty self explanatory.

Added link to content folder in case people come here to edit content

---

.github/workflows/nodejs.yml

Ref: https://github.com/stylelint/.github/pull/9

Reusable workflow

---

package-lock.json
package.json

None.
```shell
npm i @docusaurus/core @docusaurus/preset-classic
```
See also <https://docusaurus.io/blog/2022/08/01/announcing-docusaurus-2.0>
Fortunately, it seems unnecessary to change other code than `package.json`.

Update Docusaurus v2

---

package-lock.json
package.json

None.
The following commands create this change:
```shell
npm install https://github.com/stylelint/stylelint/tarball/14.10.0 --save-dev
```
```shell
npm install stylelint-config-standard@latest
```

Update stylelint deps

---

netlify.toml
package-lock.json
package.json
scripts/generate-docs.mjs
sidebars.json
src/css/custom.css

Closes #292
Tested locally. We'll need to update the tarbar version before merging.

Prepare for stylelint@15.0.0

---

package-lock.json
package.json

None; this is part of the release for `15.4.0`.

Update deps (15.4.0)

---

package-lock.json
package.json

Ref: https://github.com/stylelint/stylelint/issues/6780

Update deps including `stylelint`

---

package-lock.json
package.json

None, part of the 15.6.1 release.

Update deps (15.6.1)

---

package-lock.json
package.json

https://github.com/stylelint/stylelint/issues/6846

Update deps (15.6.2)

---

package-lock.json
package.json

https://github.com/stylelint/stylelint/issues/6882

Update deps (15.6.3)

---

docusaurus.config.js

Closes #309.
See my one review comment below.
Right now, the order is:
"Docs" "Rules" "Demo"
let me know if we'd prefer a different order!

Add "Rules" link to page header

---

package-lock.json
package.json

Ref: https://github.com/stylelint/stylelint/issues/6959
No, it's self-explanatory

Update deps (15.9.0)

---

package-lock.json
package.json
scripts/generate-docs.mjs
src/css/custom.css

Ref: https://github.com/stylelint/stylelint/pull/6937
We need to merge this pull request at the next release of Stylelint.

Introduce rule tables in rules page

---

package-lock.json
package.json
scripts/generate-docs.mjs

Closes #330
See stylelint/stylelint#6960
The recommended config will be removed in the next release, so please merge this pull request then.

Prepare Rules page tables

---

package-lock.json
package.json

Ref: https://github.com/stylelint/stylelint/issues/7038
e.g. "No, it's self-explanatory."

Update deps (15.10.0)

---

package-lock.json
package.json

Ref: https://github.com/stylelint/stylelint/issues/7050

Update deps (15.10.1)

---

package-lock.json
package.json
src/css/custom.css

Bump Stylelint to 15.10.2

---

src/css/custom.css

None.
Nicer looking for website.

Hide empty table headers

---

package-lock.json
package.json

Ref: https://github.com/stylelint/stylelint/issues/7243.

Update to Stylelint 15.11.0

---

docusaurus.config.js

Closes #361 
https://docusaurus.io/docs/api/themes/configuration#respectPrefersColorScheme

Add auto change of site theme depending on system/browser theme

---

package-lock.json
package.json

Ref https://github.com/stylelint/stylelint/issues/7378

Prepare 16.0.1

---

docusaurus.config.js
package-lock.json
package.json
scripts/generate-docs.mjs

Summary:
- Install Awesome Stylelint via npm
- Add a new `/awesome-stylelint` page
- Add a link to `/awesome-stylelint` on the top navigation bar
- Rewrite links in all the documents to Awesome Stylelint
Closes #370
Wait for stylelint/awesome-stylelint#65

Include Awesome Stylelint

---

package-lock.json
package.json

Prepare 16.1.0

---

.github/workflows/update-awesome-stylelint.yml

This change regularly updates [Awesome Stylelint](https://github.com/stylelint/awesome-stylelint) managed in `package.json`.
We can also trigger this workflow manually.
Follow-up to #372
Using a 3rd-party action: https://github.com/peter-evans/create-pull-request
---
Run `npm update awesome-stylelint` locally, and see the changes:
```diff
--- a/package-lock.json
+++ b/package-lock.json
@@ -4743,7 +4743,7 @@
},
"node_modules/awesome-stylelint": {
"version": "0.0.0",
-      "resolved": "git+ssh://git@github.com/stylelint/awesome-stylelint.git#b8214055ea1a7771622664056cee0f851f74cdb5",
+      "resolved": "git+ssh://git@github.com/stylelint/awesome-stylelint.git#7bc9da067b40ae489320ba …
```

Automate updating Awesome Stylelint

---

package-lock.json
package.json

None.
See https://github.com/stylelint/stylelint/releases/tag/16.2.0

Release 16.2.0

---

.github/dependabot.yml

Update GitHub actions by Dependabot

---

.github/workflows/update-awesome-stylelint.yml

None.
Ref https://github.com/stylelint/awesome-stylelint

Add compare link to "Update Awesome Stylelint" pull requests

---

docusaurus.config.js
package-lock.json
package.json
scripts/generate-docs.mjs

None.
This package allows to remove the custom code in the build script.
See https://github.com/incentro-dc/remark-github-admonitions-to-directives

Introduce `remark-github-admonitions-to-directives`

---

.github/workflows/nodejs.yml

See https://github.com/stylelint/.github/pull/36

Use `node-version-file` for testing on CI

---

docusaurus.config.js

If you prefer, you could put Twitter in brackets after the X instead.
None, as it's a documentation fix

Change Twitter to X

---

package-lock.json

Ref https://github.com/websockets/ws/issues/2230
This change is generated by the `npm audit fix` command.

Bump ws to latest for security fix

---

eslint.config.mjs
package-lock.json
package.json

None, as it's a dependency update
For ESLint 9.x

Bump dev dependencies

---

netlify.toml

Ref #471 
Getting `main` ready, then looking into how to do it for `master`.

Add redirect netlify app to custom domain

---

docusaurus.config.js

None.
Hide the navbar on scroll to give more screen real estate to content.

Add hideOnScroll

---

docusaurus.config.js

Ref https://github.com/stylelint/stylelint/issues/8198
Hold until next release

Remove twitter from nav

---

.github/workflows/nodejs.yml
.github/workflows/release-stylelint.yml
.github/workflows/update-awesome-stylelint.yml

None.
This PR improves several points for creating a pull request on GitHub Actions.
For details, please look at each commit.
See also the README of <https://github.com/peter-evans/create-pull-request>.

Improve creating pull request in GitHub Actions

---

docusaurus.config.js
scripts/generate-docs.mjs
sidebars.json

None.
This improves the Awesome Stylelint page:
https://stylelint.io/awesome-stylelint
- Fix the page title to exclude the `badge.svg` text.
- <img width="327" alt="image" src="https://github.com/user-attachments/assets/4044f0b7-04b4-4b2a-8223-6d1fa48bec2a" />
- Add the page to the sidebar.
- This is helpful for narrow screens like smartphones because the page link is shown in the hamburger menu.
- <img width="408" alt="image" src="https://github.com/user-attachments/assets/15c8c374-49b4-40aa-aaaf-ab585064d024" />

Improve Awesome page
