stylelint/stylelint.io

src/layouts/Page/index.css

From this:
--- 
To this:
---
As a bit too much wasted vertical real-estate on small viewports.

Tighten body margin on narrow viewports

---

src/index.global.css
src/layouts/DemoPage/index.css
src/layouts/Page/index.css

Make headings easier to read by improving contrast (make them darker).
Fix jumping content between navigation, if one of the pages doesn't have a scrollbar. Issue video: http://take.ms/mjy69
Remove double scrolling for demo page. There is still the second scrollbar, but it doesn't scroll page now.

Visual fixes

---

package.json
src/AppContainer.js
src/components/Container/index.js
src/components/Content/index.js
src/components/DefaultHeadMeta/index.js
src/components/GoogleAnalyticsTracker/index.js
src/components/Header/index.js
src/layouts/Page/index.js
src/layouts/PageError/index.js
src/layouts/RulePage/index.js

https://github.com/stylelint/stylelint.io/issues/50
Unfortunately, warnings are still here, because Phenomic uses deprecated things. Well, at least our code doesn't use them. New Phenomic version still in alpha.

Use prop-types library instead of React internal PropTypes (#50)

---

package.json
plugins/loader-plugin-markdown-transform-body-property-to-html/index.js
plugins/remark-stylelint-toc/__tests__/__snapshots__/index.test.js.snap
plugins/remark-stylelint-toc/__tests__/index.test.js
plugins/remark-stylelint-toc/index.js

Generate Table of Contents for rules and other pages. #42
For rules, TOC generated automatically and inserted before “Options” heading.
For other pages we need to add `` in markdown in `stylelint` repository. One caveat. This comment should be right before any `##` heading. `remark-toc` removes everything after TOC heading, and before next heading. So if TOC heading is right before another heading, then nothing will be deleted. I could add a workaround for this case, but I don't think we'll face it. Table of Contents usually right before headings.
I'll create a PR in the main repository with TOC after this PR merged.
Non-rule page if `` is in markdown:
Rule page:
I have concerns about rules, where there is `true` option only:
Shall we hide TOC in this case, as it useless? Shall we keep it …

Add Table of Contents generation (#42)

---

plugins/remark-stylelint-toc/__tests__/__snapshots__/index.test.js.snap
plugins/remark-stylelint-toc/__tests__/index.test.js
plugins/remark-stylelint-toc/index.js

Currently, it works for `h2`, but with this change, it could be any level.

Allow to have TOC heading before any level heading

---

package.json

This pull request seeks to switch the Jest configuration used in this repo to the newly created [Jest shared preset](https://facebook.github.io/jest/docs/en/configuration.html#preset-string) stylelint organization package [`jest-preset-stylelint`](https://github.com/stylelint/jest-preset-stylelint).

Switch Jest configuration to `jest-preset-stylelint`

---

src/layouts/DemoPage/index.js

This PR fixes a empty title and description on the demo page (https://stylelint.io/demo/).
The title and description for the demo page is created by the following script:
https://github.com/stylelint/stylelint.io/blob/d1b0c6e54786cd07959fdec53f6ae8ee23a0e735/scripts/copy-stylelint-docs.js#L68-L74
However, these aren't applied to the actual page.
The reason is that `<Helmet>` component (by `react-helmet`) is missing in the layout component for the demo page.
This PR adds `<Helmet>` and sets the correct title and description.
Fixes <https://github.com/stylelint/stylelint-demo/issues/129>

Fix title and description on demo page

---

scripts/copy-stylelint-docs.js

None, as it's a documentation fix.
No, it's self explanatory.
Fix the title on rule pages, for example ([https://stylelint.io/user-guide/rules/color-no-invalid-hex/](https://stylelint.io/user-guide/rules/color-no-invalid-hex/)).
`loader-plugin-markdown-init-head.title-property-from-content` sets the title from the first line except front matter in Markdown.
https://github.com/stylelint/stylelint.io/blob/6789e041547b9951e48d909c6658b6436a0611b9/plugins/loader-plugin-markdown-init-head.title-property-from-content/index.js#L13
But currently the first line of the rule page becomes empty.
```
---
layout:  RulePage
next:  /user-guide/rules/font-family-no-duplicate-names/
prev:  null …
```

Fix title on rule pages

---

package.json
scripts/generate-stylelint-docs.js

Revert https://github.com/stylelint/stylelint.io/pull/73, because links like https://stylelint.io/changelog#1010 stopped working, and right sidebar links to Github instead of section of the page. We need to find another solution for https://github.com/stylelint/stylelint.io/issues/69

Revert "Fix changelog Table of Content (#73)"

---

package.json
scripts/generate-stylelint-docs.js

Closes #78 
Also, to prevent such problems in the future, this enables the [`require-await`](https://eslint.org/docs/rules/require-await) rule of ESLint.

Remove unnecessary `async` from `generate-stylelint-docs.js`

---

scripts/generate-stylelint-docs.js

Closes #71 
It seems that the title tagline combination can only work with custom pages. For example, the demo page can have title `stylelint  ·  A mighty, modern style linter` if this line was not specified: `Demo.title = "Demo";`.
With markdown pages, as far as I managed to understand, it uses either the title from the metadata, if none, then uses the id, if none - then uses the name of the file - this way `props.title` is always present and it never goes in the else part of the condition (https://github.com/facebook/docusaurus/blob/v1.11.1/packages/docusaurus-1.x/lib/core/Site.js#L38-L42).

Improve homepage title

---

scripts/generate-stylelint-docs.js

By adding the `custom_edit_url` field to Markdown headers in each document.
See <https://docusaurus.io/docs/en/doc-markdown#documents> for details.

Add "Edit" button

---

package.json

We don't really need to enforce Node.js version that much. Currenly I'm stuck with Node.js 10 on my computer and can't upgrade to Node.js 12. Also I don't want to mess with different Node.js versions with NVM either.
We enforced version 12 recently (https://github.com/stylelint/stylelint.io/pull/106). `10.12.0` would be more that sufficient for contributors.

Lower Node.js version

---

website/static/css/custom.css

It's a visual tweak.
It separates the external links from the internal navigation, including search. It's a stepping stone to what the [navigation will be like](https://v2.docusaurus.io/) when we update to docusaurus@2.

Tweak nav item positions

---

.github/workflows/nodejs.yml
README.md
package.json
website/README.md

None.
Uses `prettier .`, which is introduced in version 2.
Unfortunately, it seems we need to manually specify the file extensions for `lint-staged`.

Use Prettier for all supported formats

---

.github/dependabot.yml

None.
It's easier to update the deps for this repo in one go (as, for example, the two docusaurus packages are linked).
This pull request drops the limit to one (so that the pull requests acts more like a reminder to update than anything else).

Limit dependabot PRs to 1

---

.github/dependabot.yml

Closes #277
Until Docusaurus supports React 18, we cannot update.
See https://github.com/facebook/docusaurus/issues/7264

Stop updating React via Dependabot

---

.github/dependabot.yml

None.
This change makes Dependabot Pull Requests more efficient by grouping relevant dependencies' updates.
Also, this increases `open-pull-requests-limit` because this limit's purpose is to reduce Dependabot PR noises.
This limitation will not make sense so much if using the group updates.
See also:
- [`dependabot.yml` reference](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file)
- This repository's `package.json`:
https://github.com/stylelint/stylelint.io/blob/d57da950f03e323d1058e296308c6b985098352e/package.json#L82-L106

Use Dependabot group updates

---

.github/dependabot.yml

Follow-up to #341
This PR will prevent useless PRs like #344 about React package updates.

Dependabot ignore `react-dom@18.x` like `react`

---

.github/dependabot.yml

Ref #354
Docusaurus 3.0 is out. See https://docusaurus.io/blog/releases/3.0
We can now update React to 18:
```console
$ npm view @docusaurus/core peerDependencies
{ react: '^18.0.0', 'react-dom': '^18.0.0' }
```
So, updating Docusaurus and React simultaneously should be better.

Update Dependabot group for Docusaurus and React

---

docusaurus.config.js
package-lock.json
package.json
scripts/generate-docs.mjs
src/pages/demo.js

Closes #347
See the upgrade guide: https://docusaurus.io/docs/migration/v3
Summary:
- Bump dependencies: Docusaurus and React
- Move `@docusaurus/*` from `devDependencies` to `dependencies` because the official doc describes so.
- Rewrite `docusaurus.config.js` in ESM

Upgrade to Docusaurus v3

---

docusaurus.config.js

Ref #357
I upgraded Docusaurus to v3 in #357, but I missed a breaking change for syntax highlighting.
This change adds the `prism.additionalLanguages` to the Docusaurus config.
See also:
- https://docusaurus.io/docs/migration/v3#prism-react-renderer-v20
- https://prismjs.com/#supported-languages
| Path | Before (stylelint.io) | After (this PR preview) |
|--------|--------|--------|
| `/user-guide/customize` | <img width="546" alt="image" src="https://github.com/stylelint/stylelint.io/assets/473530/e9057338-4952-4d54-aeee-6d6aefc67e10"> | <img width="524" alt="image" src="https://github.com/stylelint/stylelint.io/assets/473530/43387826-372a-49e3-9943-e7b24718e749"> |
| …

Fix syntax highlighting in code blocks

---

.github/workflows/update-awesome-stylelint.yml

This PR fixes the error with the "Update Awesome Stylelint" workflow. See the log:
```
/usr/bin/git push --force-with-lease origin create-pull-request/patch:refs/heads/create-pull-request/patch
remote: Permission to stylelint/stylelint.io.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/stylelint/stylelint.io/': The requested URL returned error: 403
Error: The process '/usr/bin/git' failed with exit code 128
```
-- https://github.com/stylelint/stylelint.io/actions/runs/7369219181/job/20054275649#step:6:89
See also https://github.com/peter-evans/create-pull-request/issues/1873
Follow-up to #374

Add missing permissions for peter-evans/create-pull-request@v5

---

.github/workflows/release-stylelint.yml
.github/workflows/update-awesome-stylelint.yml

This change automates releasing described in our maintainer guide:
https://github.com/stylelint/stylelint/blob/f4c75c911275f7c972f285495c6e037c2731981e/docs/maintainer-guide/releases.md?plain=1#L22-L28
A new workflow to update the website will be:
1. Go to this action page in `stylelint/stylelint.io`
2. Click **Run workflow**
3. Check a pull request created automatically
4. Merge the pull request
None.
We could add a GitHub workflow in `stylelint/stylelint`. But if doing so, we'd need an access token to create a pull request in `stylelint/stylelint.io`. Because managing an access token might be troublesome, I didn't adopt this idea.

Automate releasing via GitHub action

---

.github/workflows/release-stylelint.yml
.github/workflows/update-awesome-stylelint.yml

By default, `peter-evans/create-pull-request` creates a branch named `create-pull-request/patch`. This is ambiguous and may conflict.
See https://github.com/peter-evans/create-pull-request#action-inputs
None.

Specify custom branch to `peter-evans/create-pull-request` action

---

src/css/custom.css

None, as it's a documentation fix.
Nicer looking for website.
**Before:**
**After:**

Align all table columns

---

scripts/generate-docs.mjs

Necessary for https://github.com/stylelint/stylelint/pull/7983
Prism doesn't support JSONC, but its syntax highlighting works for comments in JSON.
So, this change converts automatically `jsonc` to `json` in Markdown code blocks.
See also https://prismjs.com/#supported-languages
|Before|After|
|-|-|
|<img width="547" alt="image" src="https://github.com/user-attachments/assets/d4874ed0-d4e8-49c2-b117-e27fe8717f30">|<img width="447" alt="image" src="https://github.com/user-attachments/assets/af9ca007-c9df-4af6-828d-4e4b4dfab530">|

Convert `jsonc` to `json` in code blocks

---

package-lock.json

None.
This change is generated by the `npm audit fix` command.

Bump path-to-regexp from 1.8.0 to 1.9.0

---

.github/dependabot.yml

None, as it's a documentation fix.
We can include it again now that we use ESLint 9.x

Revert 413 - include ESLint in dependabot dev group

---

docusaurus.config.js
src/css/custom.css

None.
Uses a light prism theme for code blocks in light mode. The Docusaurus site does the same, but the classic theme default does not.
Places the valid/invalid pattern indicator to the side for better compatibility with the two themes:

Fix light theme code blocks

---

docusaurus.config.js

None
When we added the "Rules" nav item, it caused a confusing active state for the "Docs" nav item:
This PR renames the first item "Home" and only activates it on that specific page so the behaviour is the same as the "Rules" and "Demo" nav item.

Fix Home nav item

---

sidebars.json

Ref https://github.com/stylelint/stylelint/pull/8235
Held until next release.

Add governance to sidebar
